# Generated by Django 6.0.1 on 2026-01-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrybut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'atrybuty',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('cena_zakupu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pozycje_zamowienia',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('wynagrodzenie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stanowisko', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Rabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('procent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aktywny', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rabaty',
            },
        ),
        migrations.CreateModel(
            name='RodzajDostawy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rodzaje_dostawy',
            },
        ),
        migrations.CreateModel(
            name='StatusPlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statusy_platnosci',
            },
        ),
        migrations.CreateModel(
            name='StatusReklamacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statusy_reklamacji',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nr_tel', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('kod_pocztowy', models.CharField(max_length=20)),
                ('nr_domu', models.CharField(max_length=10)),
                ('nr_mieszkania', models.CharField(blank=True, max_length=10, null=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresy', to='sklep.klient')),
            ],
            options={
                'db_table': 'adresy',
            },
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('hash_hash', models.CharField(max_length=255)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
            ],
            options={
                'db_table': 'konta',
            },
        ),
        migrations.CreateModel(
            name='Dostawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_dostawy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.rodzajdostawy')),
            ],
            options={
                'db_table': 'dostawy',
            },
        ),
        migrations.CreateModel(
            name='Reklamacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('data_zgloszenia', models.DateTimeField()),
                ('pozycja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.pozycjazamowienia')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.statusreklamacji')),
            ],
            options={
                'db_table': 'reklamacje',
            },
        ),
        migrations.CreateModel(
            name='Towar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('producent', models.CharField(blank=True, max_length=100, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena_jednostkowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.kategoria')),
            ],
            options={
                'db_table': 'towary',
            },
        ),
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='towar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.towar'),
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.SmallIntegerField()),
                ('tresc', models.TextField()),
                ('data_wystawienia', models.DateTimeField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
                ('towar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.towar')),
            ],
            options={
                'db_table': 'opinie',
            },
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_dostepna', models.IntegerField()),
                ('towar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.towar')),
            ],
            options={
                'db_table': 'magazyn',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.adres')),
                ('dostawa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.dostawa')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
                ('pracownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.pracownik')),
                ('rabat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.rabat')),
            ],
            options={
                'db_table': 'zamowienia',
            },
        ),
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='sklep.zamowienie'),
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_platnosci', models.DateTimeField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metoda', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.statusplatnosci')),
                ('zamowienie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platnosc', to='sklep.zamowienie')),
            ],
            options={
                'db_table': 'platnosci',
            },
        ),
        migrations.CreateModel(
            name='WartoscAtrybutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(max_length=255)),
                ('atrybut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.atrybut')),
                ('towar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wartosci_atrybutow', to='sklep.towar')),
            ],
            options={
                'db_table': 'wartosci_atrybutow',
                'unique_together': {('towar', 'atrybut')},
            },
        ),
    ]
