# Generated by Django 6.0.1 on 2026-01-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='atrybut',
            options={'verbose_name': 'Atrybut', 'verbose_name_plural': 'Atrybuty'},
        ),
        migrations.AlterModelOptions(
            name='dostawa',
            options={'verbose_name': 'Dostawa', 'verbose_name_plural': 'Dostawy'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='konto',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konta'},
        ),
        migrations.AlterModelOptions(
            name='magazyn',
            options={'verbose_name': 'Magazyn', 'verbose_name_plural': 'Magazyn'},
        ),
        migrations.AlterModelOptions(
            name='opinia',
            options={'verbose_name': 'Opinia', 'verbose_name_plural': 'Opinie'},
        ),
        migrations.AlterModelOptions(
            name='platnosc',
            options={'verbose_name': 'Płatność', 'verbose_name_plural': 'Płatności'},
        ),
        migrations.AlterModelOptions(
            name='pozycjazamowienia',
            options={'verbose_name': 'Pozycja zamówienia', 'verbose_name_plural': 'Pozycje zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='rabat',
            options={'verbose_name': 'Rabat', 'verbose_name_plural': 'Rabaty'},
        ),
        migrations.AlterModelOptions(
            name='reklamacja',
            options={'verbose_name': 'Reklamacja', 'verbose_name_plural': 'Reklamacje'},
        ),
        migrations.AlterModelOptions(
            name='rodzajdostawy',
            options={'verbose_name': 'Rodzaj dostawy', 'verbose_name_plural': 'Rodzaje dostawy'},
        ),
        migrations.AlterModelOptions(
            name='statusplatnosci',
            options={'verbose_name': 'Status płatności', 'verbose_name_plural': 'Statusy płatności'},
        ),
        migrations.AlterModelOptions(
            name='statusreklamacji',
            options={'verbose_name': 'Status reklamacji', 'verbose_name_plural': 'Statusy reklamacji'},
        ),
        migrations.AlterModelOptions(
            name='towar',
            options={'verbose_name': 'Towar', 'verbose_name_plural': 'Towary'},
        ),
        migrations.AlterModelOptions(
            name='wartoscatrybutu',
            options={'verbose_name': 'Wartość atrybutu', 'verbose_name_plural': 'Wartości atrybutów'},
        ),
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
