# Generated by Django 6.0.1 on 2026-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_alter_adres_options_alter_atrybut_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towar',
            name='cena_promocyjna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
