# Generated by Django 6.0.1 on 2026-02-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_towar_cena_promocyjna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podkategorie', to='sklep.kategoria')),
            ],
            options={
                'verbose_name': 'Podkategorie',
                'verbose_name_plural': 'Podkategorie',
                'db_table': 'podkategorie',
            },
        ),
    ]
