# Generated by Django 6.0.1 on 2026-02-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_podkategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='towar',
            name='podkategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.podkategoria'),
        ),
    ]
