# Generated by Django 6.0.1 on 2026-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_towar_podkategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kategorie/'),
        ),
    ]
